### ISSUE TITLE
TRANSCRIPTS2 - Implement server side model operation findTranscriptById

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/speak-mean#26]
Implement transcript model in /app/models/transcript/transcript.model.server.js. Implement the following function

findTranscriptById(transcriptId)

Returns Loren Iosum as a string. Returns mock data.

**Comment by tripathiamritansh** [comment]
I have implemented all the listed issues but I am not sure how should I return mock data from transcript.model.server.js.
